### ISSUE TITLE
i want to use on windows

### ISSUE THREAD

**Issue by gruming** [Bhanu1776/Nextjs14-Starter-Template#1]
https://github.com/Bhanu1776/Nextjs15-Starter-Template/tree/15d6dcbddbf07f1a5d4e539bfff7f940e39ad419/bin

I can't use the 'rm' command on Windows OS, so the template isn't installing.

so i want to use on windows

thx.

**Comment by Bhanu1776** [comment]
Thank you for bringing this to my attention!

The issue with the rm command on Windows has been identified and resolved. I’ve updated the template to ensure compatibility with Windows OS. Please pull the latest changes or re-install the package to get the updated version.

If you encounter any further issues or have additional feedback, feel free to reach out. I appreciate your patience and support!

Best regards,
Bhanu
